version: "3"
services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5001:5001"
    depends_on:
      - redis
  worker:
    environment:
      - RENDER_RESOLUTION_X=480
      - RENDER_RESOLUTION_Y=270
      - RENDER_FPS=20
      - MAX_NUMBER_FRAMES=1200
      - WORKER_TIMEOUT=600
    build:
      context: celery-queue
      dockerfile: Dockerfile
    depends_on:
      - redis
  monitor:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0 --basic_auth=${FLOWER_USER}:${FLOWER_PWD}
    depends_on:
      - redis
  redis:
    image: redis