version: "3"
services:
  web:
    environment:
      - PORT=5001
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
     - "5001:5001"
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
  worker:
    environment:
      - RENDER_RESOLUTION_X=480
      - RENDER_RESOLUTION_Y=270
      - RENDER_FPS=20
      - MAX_NUMBER_FRAMES=-1  # will throw error if submitted file has more frames than this, -1 no restriction
      - WORKER_TIMEOUT=600  # if a blender worker takes longer than this it will time out
    build:
      context: celery-queue
      dockerfile: Dockerfile
    depends_on:
      - redis
  monitor:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0 --basic_auth=${FLOWER_USER}:${FLOWER_PWD}
    depends_on:
      - redis
  redis:
    image: redis